
server:
  port: 9002

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5555/Todo
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/